# Project information
site_name: "RTEU Ders Not Şablonu"
docs_dir: '../../docs/tr'                           # Where to find the English markdown files
site_dir: '../../generated/tr'                      # Where to put the English HTML files
site_author: 'Asst. Prof. Dr. Uğur CORUH'
site_url: 'https://ucoruh.github.io/ce204-object-oriented-programming/'
site_description: >-
    Course Notes Templates

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/ce204-object-oriented-programming'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2022 Asst. Prof. Dr. Uğur CORUH

#theme:
#    name: material
#   logo: assets/images/favicon.png
#   favicon: images/favicon.png
#   palette:
#       primary: teal
#       accent: pink
#   language: en
#   feature:
#       tabs: true
#   font:
#       text: Roboto
        
# Configuration
theme:
  name: material
  custom_dir: '../../overrides/'
  # custom_dir: docs/overrides/
  #name: null
  #custom_dir: !ENV [THEME_DIR, "material"]
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Static files
  static_templates:
    - 404.html
    
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    
  palette:
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
#  palette:
#   - media: "(prefers-color-scheme: light)"
#     scheme: default
#     toggle:
#       icon: material/toggle-switch-off-outline
#       name: Switch to dark mode
#   - media: "(prefers-color-scheme: dark)"
#     scheme: slate
#     toggle:
#       icon: material/toggle-switch
#       name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: logo
    #logo: assets/images/favicon.png
    
# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY_CE204
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucoruh
    - icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/ucoruh/
    - icon: fontawesome/regular/compass
      link: https://www.scopus.com/authid/detail.uri?authorId=57218950743
    - icon: fontawesome/regular/id-card
      link: https://dblp.org/pid/230/0394.html
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ucoruh/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/my-orcid?orcid=0000-0003-4193-8401
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ugurcoruh/
    - icon: fontawesome/regular/moon
      link: https://publons.com/researcher/1540204/ugur-coruh/
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=KIU4ltMAAAAJ&hl=tr
    - icon: fontawesome/regular/clipboard
      link: https://avesis.erdogan.edu.tr/ugur.coruh
    - icon: fontawesome/regular/user-circle
      link: https://www.ugurcoruh.com/
      
  alternate:
  
    - name: English
      link: /en/ 
      lang: en
      
    - name: Türkçe
      link: /tr/
      lang: tr

      
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
      lang: tr    # Set language for search
  - git-revision-date-localized
  - minify:
      minify_html: false

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Page tree
nav:
  - AnaSayfa: index.md
  - Ders İzlencesi: syllabus/syllabus.md
  - Ders Modülleri:
    - Hafta-1 (Örnek-1): week-1/week-1.md
    - Hafta-2 (Örnek-2): week-2/week-2.md
    - Hafta-3 (Örnek-3): week-3/week-3.md
    - Hafta-4 (Örnek-4): week-4/week-4.md
    - Hafta-5 (Örnek-5): week-5/week-5.md
    - Hafta-6 (Örnek-6): week-6/week-6.md
    - Hafta-7 (Örnek-7): week-7/week-7.md
    - Hafta-8 (Örnek-8): week-8/week-8.md
    - Hafta-9 (Örnek-9): week-9/week-9.md
    - Hafta-10 (Örnek-10): week-10/week-10.md 
    - Hafta-11 (Örnek-11): week-11/week-11.md 
    - Hafta-12 (Örnek-12): week-12/week-12.md
    - Hafta-13 (Örnek-13): week-13/week-13.md
    - Hafta-14 (Örnek-14): week-14/week-14.md
    - Hafta-15 (Örnek-15): week-15/week-15.md
    - Hafta-16 (Örnek-16): week-16/week-16.md
  - Lisans: license.md
  - Geçmiş: changelog/index.md

